# Generated by Django 3.1.1 on 2021-06-05 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('att_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('att_hour', models.CharField(max_length=20)),
                ('att_date', models.DateField(default=datetime.datetime(2021, 6, 5, 14, 1, 45, 190546, tzinfo=utc))),
                ('att_time', models.TimeField(default=datetime.datetime(2021, 6, 5, 14, 1, 45, 190546, tzinfo=utc))),
                ('att_duration', models.IntegerField(default=10)),
                ('att_code', models.CharField(editable=False, max_length=6, unique=True)),
                ('att_students', models.ManyToManyField(to='account.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=35)),
                ('faculty_nos', models.IntegerField(default=0)),
                ('course_nos', models.IntegerField(default=0)),
                ('student_nos', models.IntegerField(default=0)),
                ('since', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('course_faculty', models.CharField(default='', max_length=200)),
                ('course_students', models.CharField(default='', max_length=200)),
                ('part_count', models.IntegerField(default=0)),
                ('course_atts', models.ManyToManyField(to='vclass.Attendance')),
                ('dep_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vclass.department')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('ass_id', models.AutoField(primary_key=True, serialize=False)),
                ('ass_name', models.CharField(max_length=20)),
                ('ass_posted', models.DateField()),
                ('ass_due', models.DateField()),
                ('ass_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vclass.courses')),
            ],
        ),
    ]
