# Generated by Django 3.1.1 on 2021-06-05 14:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210605_1931'),
        ('vclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 5, 14, 25, 2, 604602, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_time',
            field=models.TimeField(default=datetime.datetime(2021, 6, 5, 14, 25, 2, 604602, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='courses',
            name='course_students',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_students',
            field=models.ManyToManyField(to='account.Student'),
        ),
    ]
