# Generated by Django 3.1.1 on 2021-06-05 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0002_auto_20210605_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='att_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='att_end',
            field=models.TimeField(default=datetime.datetime(2021, 6, 5, 15, 32, 8, 67031, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='att_start',
            field=models.TimeField(default=datetime.datetime(2021, 6, 5, 15, 32, 8, 67031, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 5, 15, 32, 8, 67031, tzinfo=utc)),
        ),
    ]
