# Generated by Django 3.1.1 on 2021-06-06 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0006_auto_20210606_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 6, 27, 38, 744942, tzinfo=utc)),
        ),
    ]
