# Generated by Django 3.1.1 on 2021-06-06 11:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210605_1931'),
        ('vclass', '0013_auto_20210606_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='ass_for',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_assign',
            field=models.ManyToManyField(to='vclass.Assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ass_due',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ass_posted',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 11, 1, 31, 129751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 11, 1, 31, 129751, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 6, 11, 1, 31, 129751, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Ass_submission',
            fields=[
                ('sub_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
