# Generated by Django 3.1.1 on 2021-06-07 17:19

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210605_1931'),
        ('vclass', '0015_auto_20210606_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('graded', models.BooleanField(default=False)),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_files', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='vclass/static/assignment_submissions'), upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='ass_file',
            field=models.FileField(max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='vclass/static/assignment'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 17, 19, 29, 567682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 17, 19, 29, 567682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 17, 19, 29, 567682, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Ass_submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='files',
            field=models.ManyToManyField(to='vclass.SubmissionFiles'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submissions',
            field=models.ManyToManyField(to='vclass.Submission'),
        ),
    ]
