# Generated by Django 3.1.1 on 2021-06-14 05:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210605_1931'),
        ('vclass', '0020_auto_20210608_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='att_students',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 14, 5, 5, 58, 475662, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='AttendanceSubmission',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('stamp', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='sub',
            field=models.ManyToManyField(to='vclass.AttendanceSubmission'),
        ),
    ]
