# Generated by Django 3.1.1 on 2021-06-14 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0021_auto_20210614_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 14, 5, 10, 8, 488531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 5, 10, 8, 488531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 5, 10, 8, 488531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendancesubmission',
            name='stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
