# Generated by Django 3.1.1 on 2021-06-15 17:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0022_auto_20210614_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 17, 41, 38, 939009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 17, 41, 38, 939009, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 17, 41, 38, 939009, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='duration in minutes')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vclass.courses')),
            ],
        ),
    ]
