# Generated by Django 3.1.1 on 2021-06-15 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0023_auto_20210615_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 15, 18, 41, 33, 18459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 18, 41, 33, 19457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 18, 41, 33, 18459, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1000)),
                ('option1', models.CharField(max_length=300)),
                ('option2', models.CharField(max_length=300)),
                ('option3', models.CharField(max_length=300)),
                ('option4', models.CharField(max_length=300)),
                ('correct', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], max_length=7)),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vclass.quiz')),
            ],
        ),
    ]
