# Generated by Django 3.1.1 on 2021-06-16 15:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0024_auto_20210616_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 16, 15, 39, 38, 808737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 15, 39, 38, 808737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 15, 39, 38, 808737, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct',
            field=models.CharField(max_length=300),
        ),
    ]
