# Generated by Django 3.1.1 on 2021-06-17 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0026_auto_20210617_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 12, 57, 2, 520703, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 17, 12, 57, 2, 482712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 12, 57, 2, 482712, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 12, 57, 2, 482712, tzinfo=utc)),
        ),
    ]
