# Generated by Django 3.1.1 on 2021-06-18 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0027_auto_20210617_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 18, 15, 8, 59, 815348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 8, 59, 815348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 8, 59, 815348, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='stamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 8, 59, 877767, tzinfo=utc)),
        ),
    ]
