# Generated by Django 3.1.1 on 2021-06-18 15:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vclass', '0029_auto_20210618_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='att_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 18, 15, 43, 29, 961215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 43, 29, 961215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='att_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 18, 15, 43, 29, 961215, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='stamp',
            field=models.DateTimeField(null=True),
        ),
    ]
